### ISSUE TITLE
Incompatible with jQuery 1.8

### ISSUE THREAD

**Issue by chrisfrancis27** [fnagel/jquery-ui#261] opened 2012-08-17 09:25 UTC
Hovering over selectmenu items throws a SyntaxError when used with jQuery 1.8:

> SCRIPT5022: Syntax error, unrecognized expression: li:not(.ui-selectmenu-group).slice(3,4) 
> jquery-1.8.0.js, line 4512 character 2

I believe this is due to an internal change with the way the `:not` pseudo-selector is handled in the new Sizzle engine as I have experienced this in other code as well.  Using the `.not()` method on a jQuery object should still work as expected though.

**Comment by Peinkillar** [comment] 2012-08-28 14:19
For me that does not change anything. The problem is that _selectedOptionLi() function is returning ".splice(-1)" when this._selectedIndex() == -1. It is related to this problem: http://stackoverflow.com/questions/12002783/jquery-future-elements-selector

Has to be something like this:

_selectedOptionLi: function () {
    return this._optionLis.find(":eq(" + this._selectedIndex() + ")");
}

But then this._selectedIndex() == -1 has to be handled anyway.

**Comment by moikano** [comment] 2012-08-29 23:53
I think the problem is in **items (A)**'s `bind('mouseout.selectmenu blur.selectmenu', function() {...})` when use `if ($(this).is(self._selectedOptionLi().selector)) {`, as pointed in the stackoverflow's post (about **.selector** property) linked by @Peinkillar.

In 836e026b1942dcbbf37fae3338bea77a40803754 I fixed it with `if ($(this).attr('aria-selected') == 'true') {` and now it works properly with jQuery 1.8.

Probably there is a better way, but now for me is ok.

**Comment by Peinkillar** [comment] 2012-08-30 07:00
Yes, that works!
Thanks

**Comment by fnagel** [comment] 2012-08-30 18:58
Sorry for the late response, I configured something wrong when GitHub changed there notification system and therefore did not receive any emails :-(

I will take a look in this as soon as possible. Information about jQuery 1.8: http://blog.jquery.com/2012/08/09/jquery-1-8-released/

**Comment by fnagel** [comment] 2012-08-30 19:13
This is the correct reference to the above revision (above one points to my repo, wired enough, its with the correct code displayed): https://github.com/moikano/jquery-ui/commit/836e026b1942dcbbf37fae3338bea77a40803754

**Comment by fnagel** [comment] 2012-10-01 22:29
Please see #269 for more infos about this issue. 

Ive pushed a fix and my tests seem promising. Please test and give feedback!

**Comment by fnagel** [comment] 2012-10-03 21:32
I've updated to jQuery 1.8.2 / UI 1.8.20 and it seems to work pretty nice. Please give feedback!

**Comment by fnagel** [comment] 2012-10-12 20:39
Please give feedback!

**Comment by moikano** [comment] 2012-10-13 03:26
Sorry for the extreme delay... yes, I confirm that your tests (and my project with jQ 1.8.2 / UI 1.8.24) works perfectly with your last 73def95cb9d9584b8067660f5cb8429ab3235585 : the problem was the **.selector** property.

Thanks a lot!

**Comment by fnagel** [comment] 2012-10-13 18:42
Thanks for the feedback. Next: jQuery UI 1.9.0 :-)

Closed, please reopen if needed.

**Closed as completed by fnagel** 2012-10-13 18:42 UTC
Labels: bug, needs_feedback, help_wanted, Update-jQuery-version
