### ISSUE TITLE
Tab based navigation does not work on Firefox

### ISSUE THREAD

**Issue by mLihs** [fnagel/jquery-ui#334] opened 2014-03-19 08:10 UTC
On Firefox 26+, it's not possible to set the focus to the  selectmenu by using the Tab Key.
All other browsers seems to be fine.

http://view.jqueryui.com/master/demos/selectmenu/default.html

**Comment by fnagel** [comment] 2014-03-19 11:46
Please note: this bugtracker is for my fork of selectmenu, not the official, not yet released one of jQuery UI itself. You should report issues on the wiki page (http://wiki.jqueryui.com/w/page/12138056/Selectmenu) next time. 

Anyway, thanks for reporting this issue :-)

I'm not able to reproduce this in FF28 (stable since today) or FF29 (beta).
What are the exact steps to reproduce?

**Comment by mLihs** [comment] 2014-03-19 14:07
Hey Felix,

i use the last version from your master Branch ->  https://github.com/fnagel/jquery-ui.git
- jQuery UI Selectmenu version 1.5.0pre

the newer one seems to work. 
For several reasons i have to use jQuery 1.8.3.
Wehre can i get the Version that you use at :

```
http://view.jqueryui.com/master/demos/selectmenu/default.html
```

and is it compatible with jQuery 1.8.3.

Thanks 
Best martin

**Comment by fnagel** [comment] 2014-03-19 15:06
You are using my fork of the old filament group selectmenu widget. The demo you are linking to is part of the jQuery UI master branch (https://github.com/jquery/jquery-ui) with a new, unreleased selectmenu widget. The new version will not work with jQuery 1.8.3. 

I'm not able to reproduce the issue with the "old" selectmenu widget. At least not in the default demo, see http://jsfiddle.net/fnagel/GXtpC/

**Comment by mLihs** [comment] 2014-03-19 15:30
With the Demo from  > http://jsfiddle.net/fnagel/GXtpC/ i still can reproduce the issue. I use OSX 10.9.2 with FF 27.0.1 and 28.0. What Version of FF do you use.

**Comment by fnagel** [comment] 2014-03-19 15:38
I've tested on Win7 with FF 28 and 29beta. Any chance to test a Windows machine?

You say its not possible to focus any selectmenu button by using tab? Is it possible one has gained focus by mouse? 
What are the exact steps to reproduce?

**Comment by mLihs** [comment] 2014-03-19 16:16
i tested it on windows 7 with FF 27 and there it works fine. So it's FF - OSX problem.
Yes i can achieve a gained focus by using the mouse - if i press now the tab key (focus on the 1. Selectbox), the focus jumps directly to the browser address field.

**Comment by fnagel** [comment] 2014-06-01 12:31
I have not the possibility to test (and therefor fix) issues on OSX but I asked another team member and he was not able to reproduce this on latest FF. 

Did you try testing with the latest beta 1.11.0 beta2?

**Comment by fnagel** [comment] 2014-06-27 17:15
Any feedback on this issue?

**Comment by fnagel** [comment] 2014-09-01 09:18
Closed as no feedback was given.

Please use the official bug tracker of jQuery UI for issue regarding the official widget.

**Closed as completed by fnagel** 2014-09-01 09:18 UTC
Labels: bug, needs_feedback, NewOfficialSelectmenu
