### ISSUE TITLE
Z-Index of selectmenu classes are being overridden by element

### ISSUE THREAD

**Issue by juja** [fnagel/jquery-ui#95] opened 2011-04-03 19:30 UTC
On a page with an OpenLayers map, the selectmenu dropdown appears behind the map so cannot select an option, the control belongs the map.

The class ui-selectmenu-menu has attribute z-index, but when i inspect the element with firebug i found an element attribute z-index set to 0 that override the class one.

So i cannot set z-index with CSS. If i change the element value with JQuery(dropdown is open), the menu is ok but when it is reopened the value is reseted to 0.

Thanks in advance.

**Comment by fnagel** [comment] 2011-04-16 00:23
Would you please post a example as Im not able to reproduce your issue.

**Comment by juja** [comment] 2011-04-17 18:12
How i can paste html code here?

**Comment by fnagel** [comment] 2011-04-17 20:43
Use a pastebin or better, post a working example using this: https://github.com/fnagel/jquery-ui/issues/61

**Comment by juja** [comment] 2011-04-17 21:04
Here is the example: http://jsfiddle.net/juja/XqJXR/

**Comment by michaelcaplan** [comment] 2011-05-02 12:12
Line 773 (https://github.com/fnagel/jquery-ui/blob/selectmenu/ui/jquery.ui.selectmenu.js#L773) seems to force the zIndex to be forced to 0 on the div's inline style.  Removing that line fixes the issue.

If the goal is to determine the zIndex of the select element and apply it to the generated div, zIndex() seems to always return 0 (at least in Chrome & Firefox).  jQuery's .css() method as an alternative seems to return 'auto' all the time. (?)

There must be a good way to accomplish this...

**Comment by juja** [comment] 2011-05-05 14:37
Thanks for your comments. 
Searching in google i found a bug description about zIndex and JQuery(http://bugs.jqueryui.com/ticket/5110) where specify that element.zIndex() works only if the element is positioned(absolute, relative, or fixed).

I added "position: relative;" to my element's CSS class and it works!, therefore selectmenu library must check if the "<select>" is positioned before use element.zIndex()

Thanks!

**Comment by fnagel** [comment] 2011-05-23 18:01
Sorry about the long waiting time, but I had an surgery and was not able to work on the selectmenu widget the last few weeks.

@juja and @michealcaplan
So when using "position: relative;" fix this problem this patch should be applied to the delivered CSS. Could you please explain where to add the position: inline style?

**Comment by juja** [comment] 2011-05-26 01:00
Hi:

Just setting the parameter "position: relative; z-index: 1000;" in the class of the select element, in the CSS file is sufficient.

But i'm not using that solution right now because setting the z-index of the select element, this stay on top of other menu that i have in the site.

**Comment by fnagel** [comment] 2011-05-26 07:35
With select element you talk about the original select as we use zIndex:
this.element.zIndex() in refreshPosition, correct?

**Comment by juja** [comment] 2011-05-26 13:15
Exactly

**Comment by fnagel** [comment] 2011-05-29 18:49
I did some changes to ensure zIndex is able to retrieve the zIndex. So you're able to define you z-index via CSS (class: ui-selectmenu-menu). Please test and give feedback!

Related issue: https://github.com/fnagel/jquery-ui/issues/23

**Comment by juja** [comment] 2011-05-30 15:29
if i set z-index to the original select element this override the ui-selectmenu-menu's value, without set this value(and with your last modification) it works.

Thanks for your time.

**Comment by fnagel** [comment] 2011-05-31 09:23
So this issue could be closed as fixed.

**Closed as completed by fnagel** 2011-05-31 09:23 UTC
Labels: bug, needs_feedback
