### ISSUE TITLE
selectmenu does not work when inside a jQuery Dialog

### ISSUE THREAD

**Issue by vdcprivate** [fnagel/jquery-ui#23] opened 2010-10-18 15:15 UTC
I am trying to use selectmenu inside a jQuery modal dialog but it does not work.

I have created a small sample [here](https://docs.google.com/leaf?id=0B9IY0bJiYPdrZDhkZTVhMWQtZjEzOS00OTc3LWIxNmUtNzg4NzRiZTdjMTBi&hl=it) that reproduce the bug. 

Keep up the good work!

**Comment by vdcprivate** [comment] 2010-10-23 09:57
Can I have a confirm that others have the same problem? I mean that this is a bug....

Also, How can I label it as a bug?

**Comment by fnagel** [comment] 2010-10-25 22:09
I can confirm this error. Please check my latest comment:
http://filamentgroup.com/lab/jquery_ui_selectmenu_an_aria_accessible_plugin_for_styling_a_html_select/#commentNumber278

This fix is already commited.

**Comment by vdcprivate** [comment] 2010-10-25 23:25
Hello,
thank you very much for your support!  Great job Felix! :)

For what concerns my tests, this bug can be considered closed.

**Comment by dannycohn** [comment] 2010-11-15 15:37
This issue is not resolved.  The "fix" committed was to add a zindex of 1005 to the css.  What if the dialog in question has a greater zindex (either set manually or due to dialog stacking)?  A better solution would be to add in the following in _refreshPosition before the call to the position plugin:

<code>
this.list.css({
zIndex: this.element.zIndex()
});
</code>

**Comment by fnagel** [comment] 2010-11-15 19:01
So you need to higher the z-index attr of the list instead of the list itself? What if the lists does not have a specified z-index? What if its to low? Why not do this manually by CSS, case by case?

Is zIndex() a jQuery function?

**Comment by dannycohn** [comment] 2010-11-15 19:28
<code>this.list</code> is created by just calling <code>$('<ul...')</code> which means that the UL is appended to the body.  Therefore it doesn't inherit z-index from the dialog because it isn't in the dialog.  zIndex is a function provided by jQuery UI Core as of version 1.8.  It provides the effective z-index of an element.  Meaning if an element has no set z-index but is contained within an element that has a z-index of 1000, calling zIndex on the child element will return the z-index of the parent.  Doing it this way guarantees that the UL has the same z-index as the actual select element, so it will appear above any number of dialogs

**Comment by fnagel** [comment] 2010-11-28 23:14
Nice, thanks for pointing that out and your contribution.
You fix is submitted to the repo. Please test if this issue is fixed so I can close it.

**Comment by cburgdorf** [comment] 2010-12-13 13:44
Confirmed :-)

**Comment by fnagel** [comment] 2010-12-14 00:02
Nice, thanks for your feedback cburgdorf. 

Closed, please reopen if you running into issues.

**Closed as completed by fnagel** 2010-12-14 00:02 UTC
Labels: bug, needs_feedback

**Comment by fnagel** [comment] 2011-05-29 18:39
Related issue: https://github.com/fnagel/jquery-ui/issues/95
