### ISSUE TITLE
Selects random list item from Main 'Button'

### ISSUE THREAD

**Issue by YellowSwordfish** [fnagel/jquery-ui#92] opened 2011-03-29 20:06 UTC
When there is not enough real estate top or bottom to display the full list, clicking on the 'button' to open the list actually selects one of the list items instead.
This is using selectmenu as a dropdown select list replacement. All items in the select list are urls.
(Browsers FF4/IE9 both OS/X and Win - No public site available yet)

**Comment by fnagel** [comment] 2011-04-16 00:18
Please provide a demo (see here how to easily post a bug: https://github.com/fnagel/jquery-ui/issues/61).

**Comment by YellowSwordfish** [comment] 2011-04-16 13:10
As I said originally there is no public facing example I can show you. I will not be able to get that up for at least another 3 months at which time we may have had to abandon using selectmenu which would be very sad.
The best I could offer at the moment would be a screen video of the effect. If that is of interest then please let me know where to send it I can can get on to make that for you. Sorry! And I can provide code example of course.
Selectmenu is looking so promising I would welcome any opportunity to help you with problem identification.
Andy

**Comment by fnagel** [comment] 2011-04-16 14:16
Am I right your problem occurs with selectmenu placed like the one of the bottom of this site? http://www.taxofit.de/

If you're not able to post a example which reproduces the issue Im afraid I can not give you support here, as Im not able to reproduce the issue.A video would be helpfull but Im not quite sure if its enough, so please post as much code snippets as possible. 

Are you sure you're using the latest version of the widget?

**Comment by fnagel** [comment] 2011-06-01 19:31
Please give feedback!

**Comment by YellowSwordfish** [comment] 2011-06-06 10:51
Did you get the video link I sent?

**Comment by fnagel** [comment] 2011-06-06 22:49
No, Im sorry. Where did you sent the link?

**Comment by YellowSwordfish** [comment] 2011-06-07 09:10
Apologies. Too many distractions!
I have made a small video of the effect. You can view it here:
http://www.yellowswordfish.com/video/SelectMenu-small.mov

We are the authors of a WordPress forum plugin. You will see that the SelectMenu operates fine when it has the available space but when there is not enough browser space to display it it pops up and automatically selects one of the items. In this case they are all links to other forum pages so the selected page is simply loaded.

This may be an issue for anyone with a potentially long list to display.

I have updated the code to your latest build but the problem remains.
Thanks - Andy

**Comment by fnagel** [comment] 2011-06-07 23:56
Ahh I see. This is a problem because of a very long list, probanly with more height than the browser window itself, correct? I must resize the browser window in order to see the problem.

There is currently no functionality which tests for this but you should try using the maxHeight option. Selectmenu will show a scrollbar if needed. Perhaps this could fix you problem?

Could you please post the select HTML you are using in the video?
I would love to link your forum to the real world examples if this would be ok for you. Is there a public demo?

**Comment by fnagel** [comment] 2011-06-28 23:18
There has been a change in the height algorythm, please test the latest commit and give feedback. See here for more info: https://github.com/fnagel/jquery-ui/issues/133#issuecomment-1384607
Please try with maxHeihgt options set and without!

I would love to link your forum to the real world examples if this would be ok for you. Is there a public demo?

**Comment by YellowSwordfish** [comment] 2011-06-29 11:39
Apologies for the delay. We had a death in the family which took me away from home for several weeks.

I have downloaded your latest development build and yes - this does improve the behaviour remarkably. With or without MaxHeight set. However, it still shows the same behaviour the very first time it is opened when the display space is limited. Then subsequent openings behave very well. So generally things are looking pretty good. Thank you.

I do have one simple request although I understand that it is non-standard. For the reason of supplying our often non-technical users with simplified CSS, we do not append SelectMenu to 'body' but edit the code to target a specific div id. I wondered if it would be possible for that to be added to the initialising option array? Yes - non-standard UI I know but it is worth asking!

I would expect a public facing site using our latest code utilising selectmenu will be coming sometime late July or maybe early August but not before. I am more than happy for you to link to it as a demonstration of selectmenu in use and will let you know when it goes live.

Thanks for everything - it is essentially a great component and I will keep a watch here for the next 'official' release.
Andy

**Comment by fnagel** [comment] 2011-07-28 22:51
Naah, sorry to hear about your loss.

Mhhhhh. First opening is wrong, all following work correct. I would need a test case for that but I will give it a try. Please provide a demo fiddle or a zip.

Im currently planning some refactoring within the HTML injecting. Please open a new issue for that request and I will see what I can do :-)

Great, please send me a message or use the issue for real world examples: https://github.com/fnagel/jquery-ui/issues/60

Please see here as there actually is a "official" release ;-)
https://github.com/fnagel/jquery-ui/issues/140

**Comment by fnagel** [comment] 2011-08-31 19:01
There is a feature request for your appedTo question. See here: #155 I will implement this soon!

I will close this issue if there are no more open questions, ok?

**Comment by YellowSwordfish** [comment] 2011-08-31 19:23
Apologies for being quiet.
We are hoping and planning to take the new code live over the next 1 or 2 weeks and I was going to wait and let you know so you can see the selectmenu in action with the current issues. 
I will post here as soon as it is there for you to look at.
Thanks
Andy

**Comment by YellowSwordfish** [comment] 2011-09-06 11:33
You can see the selectmenu in action now on our site. This is still very much an alpha version so there amy be other issues! 
You should see the selectmenu - 'New and Recently Updated Topics' . It will still misbehave if the browser window is too small to accommodate the whole list.
see here: http://simple-press.com/support-forum/
Thanks
Andy

**Comment by fnagel** [comment] 2011-10-10 21:20
Would you mind testing the latest version? I hopefully get rid of all these kind of problems. 
You would do me a favor as the latest release is about to be tagged as v1.2.

**Comment by YellowSwordfish** [comment] 2011-10-16 10:16
Sorry - I have been on a long vacation.
Our live site is updated to the latest and I am afraid the problem 
persists - although perhaps not quite so frequently.
Andy

> ---
> 
>   Felix Nagel 
> mailto:reply@reply.github.com
> 10 October 2011 22:20PM
> 
> Would you mind testing the latest version? I hopefully get rid of all 
> these kind of problems.
> You would do me a favor as the latest release is about to be tagged as 
> v1.2.

**Comment by fnagel** [comment] 2011-10-17 23:14
Mhhh damn. Im not quite sure if I can afford the time to fix this unclean code base. Too many maintainers and a wrong start with the focus handling. Did you tried using selectmenu with a fitting maxHeight option (250 or something)? This would be a workarround.

By the way the demo above () does not use the latest version and is modified. Additonally I have no idea how you trigger the links, but it seems you are not using the API callback events.

You could try the latest version of the new built from scratch selectmenu widget which will be part of one of the next major jQuery UI releases: #140 Its pretty straight forward and its features and API should be stable and will not change any more.

**Comment by YellowSwordfish** [comment] 2011-10-18 09:19
Thanks Felix

The latest version does not resolve these specific issues but also seems 
to have one or two other display issues (like a disassociated scrollbar 
for example).

Both of the instances of selectmenu DO include a maxHeight directive and 
we would really rather not make them any smaller.

The only modification we made to your code was to change the appendTo 
'body' to append instead to a specific div.

You say 'You could try the latest version of the new built from scratch 
selectmenu widget'... Where is this please? I can only find your own 
code - nothing else?

The main reason we wanted to try and use your SelectMenu plugin was 
because we would like to have both entry specific colours and an icon on 
some entries - both supported perfectly in SelectMenu. I have been 
unable to locate another jQuery plugin that gives us these options. If 
you know of one then I would try it of course. Secondary to this we were 
also hoping to standardise on the jQuery ui option but will look 
elsewhere if needed.

Thanks you for your time and help in trying to resolve these issues.

Andy

> ---
> 
>   Felix Nagel 
> mailto:reply@reply.github.com
> 18 October 2011 00:14AM
> 
> Mhhh damn. Im not quite sure if I can afford the time to fix this 
> unclean code base. Too many maintainers and a wrong start with the 
> focus handling. Did you tried using selectmenu with a fitting 
> maxHeight option (250 or something)? This would be a workarround.
> 
> By the way the demo above () does not use the latest version and is 
> modified. Additonally I have no idea how you trigger the links, but it 
> seems you are not using the API callback events.
> 
> You could try the latest version of the new built from scratch 
> selectmenu widget which will be part of one of the next major jQuery 
> UI releases: #140 Its pretty straight forward and its features and API 
> should be stable and will not change any more.

**Comment by fnagel** [comment] 2011-10-18 23:12
Mhh ok, if you dont like the selectmenu to have a scrollbar its not possible atm I guess.

You will find it at the official jquery-ui GitHub account, in the Selectmenu branch: https://github.com/jquery/jquery-ui/tree/selectmenu
Sorry, ive updated #140.

Sorry Im not quite aware of other Selectmenu plugins. Did you check the Wiki page in #140? There is a section called 'Related plugins'.

If you like to use more jQuery UI widget you should take a look arround in the mentioned Wiki. There are tons of new UI widgets which are pretty usable. Some of them will be released to the official downloads soon.

**Comment by YellowSwordfish** [comment] 2011-10-19 20:43
Thanks Felix.
I will keep a close eye on progress.
Andy

> ---
> 
>   Felix Nagel 
> mailto:reply@reply.github.com
> 19 October 2011 00:12AM
> 
> Mhh ok, if you dont like the selectmenu to have a scrollbar its not 
> possible atm I guess.
> 
> You will find it at the official jquery-ui GitHub account, in the 
> Selectmenu branch: https://github.com/jquery/jquery-ui/tree/selectmenu
> Sorry, ive updated #140.
> 
> Sorry Im not quite aware of other Selectmenu plugins. Did you check 
> the Wiki page in #140? There is a section called 'Related plugins'.
> 
> If you like to use more jQuery UI widget you should take a look 
> arround in the mentioned Wiki. There are tons of new UI widgets which 
> are pretty usable. Some of them will be released to the official 
> downloads soon.

**Comment by fnagel** [comment] 2011-11-02 18:37
I will close this issue for now. Please open a new issue if needed.

**Closed as completed by fnagel** 2011-11-02 18:37 UTC
Labels: bug, needs_feedback
