### ISSUE TITLE
Sometimes the horizontal alignment of dropdown menu is incorrect

### ISSUE THREAD

**Issue by ianthedev** [fnagel/jquery-ui#326] opened 2014-02-14 03:34 UTC
Today my client informed me that the dropdown menu I implemented for him is incorrect in horizontal alignment in a big screen.

Actually the client inform me about that is not the first time I encountered such an issue. In my previous projects, I sometimes noticed it, too. It sometimes occurs, and sometimes it fixes itself. That's odd.

![fig 1](https://f.cloud.github.com/assets/3986852/2167941/82e00306-9528-11e3-9ec0-a869304b2949.jpg)

**Comment by fnagel** [comment] 2014-02-14 08:09
Please provide a demo fiddle #61 to reproduce the issue.

**Comment by ianthedev** [comment] 2014-02-14 08:12
Can't really provide a demo now. Because I don't know when it will occur. Sometimes it occurs, and sometimes it doesn't. I have many such experiences in the past.

**Comment by fnagel** [comment] 2014-02-14 10:31
In this case I must assume this due to your CSS and / or HTML Structure and / or interfering JavaScript. Dropdown style is based purely upon the jQuery UI Position Plugin which is pretty solid.

Additionally, there were no other positioning issues reported lately.

**Comment by ianthedev** [comment] 2014-02-14 10:55
Okay. Thanks.

**Comment by ianthedev** [comment] 2014-03-07 02:09
Could you please advise on the possible cause? Like what kind of CSS and / or HTML structure might affect the horizontal position? It is still happening in my another project.

**Comment by fnagel** [comment] 2014-03-07 14:17
Hard to say. Try firebug or a similar HTML inspector to find out what could cause the issue.

**Comment by ianthedev** [comment] 2014-05-21 03:07
This issue keeps happening. And I really don't know what the problem is. Sometimes the dropdown is even way off to the right. Could you please help check the problem?

[Here is a demo](http://goo.gl/TmqeZF).

**Comment by fnagel** [comment] 2014-06-01 12:24
Sorry - I see no obvious issues on your page but you heavily modified the Selectmenu button CSS. Try to revert this to default, perhaps this broke the positioning functionality.

Try to remove parts of the html and css until you find the issue triggering part of your code.

**Comment by ianthedev** [comment] 2014-06-01 14:29
I found a way to solve the left offset issue. If the `body` has a scrollbar (you can test that by adding css `overflow: scroll`), the issue is gone. Do you have an idea about the cause?

**Comment by fnagel** [comment] 2014-06-01 20:18
No, but it seems you're right. Could it be this is related to the \* { box-sizing: border-box; } statement?

**Comment by ianthedev** [comment] 2014-06-02 03:43
I just tested that. Nope.

**Comment by fnagel** [comment] 2014-09-30 15:37
Any feedback on this issue?

**Comment by ianthedev** [comment] 2014-09-30 15:41
Not actually a feedback, but I still couldn't get it fixed so I had to manually adjust it using "open" event.

**Comment by fnagel** [comment] 2014-09-30 15:42
Mhh ok, so I could probably close this issue, right?

**Comment by ianthedev** [comment] 2014-09-30 15:43
Yeah.

**Closed as completed** 2014-09-30 15:51 UTC
Labels: bug, needs_feedback
