### ISSUE TITLE
List width incorrectly computed.

### ISSUE THREAD

**Issue by prodigitalson** [fnagel/jquery-ui#41] opened 2010-11-25 06:50 UTC
When omitting one of the width options the width of the widget is not calculated properly. Changing the following helps but the button is still misaligned right next to the option text:

//original selectmenu width
var selectWidth = this.element.width();

to:

//original selectmenu width
var selectWidth = this.element.outerWidth();

jQuery ui version 1.8.6
jQuery version 1.4.4

**Comment by fnagel** [comment] 2010-11-29 00:21
Would you please upload a example zip or provide a sample css style so i can reproduce this issue as Im not sure if I understand your problem. 

The new select element is not as large as the original one when using CSS code like this:
    select { width: 200px; padding: 20px; border: 10px solid red; }

Is this correct?

**Comment by prodigitalson** [comment] 2010-11-29 04:39
Actually no although that might be the case. I am not supplying a width to my form elements so they are dependent upon the contents. Even though all the image resources dont come through you can still roughly see whats happening here: http://jsfiddle.net/gb6Nu/

Notice how the text is clipped. This only seems to be in FF 3.6.12... it seems fine in Safari/Webkit.

**Comment by fnagel** [comment] 2010-12-10 11:54
Please provide a fully working example zip as I'm not able to reproduce this issue.

**Comment by fnagel** [comment] 2011-01-31 20:37
Closed as no feedback was given. Please re-open if necessary.

**Closed as completed by fnagel** 2011-01-31 20:37 UTC
Labels: bug, needs_feedback
