### ISSUE TITLE
Uncaught Error: cannot call methods on button prior to initialization; attempted to call method 'widget'

### ISSUE THREAD

**Issue by danielkoch** [fnagel/jquery-ui#299] opened 2013-04-23 06:14 UTC
I have a problem with selectmenu in combination with the jQuery UI Button component.

I prepared a Demo:
http://jsfiddle.net/danielkoch/zRFSr/

This Demo will NOT work (JS error: Uncaught Error: cannot call methods on button prior to initialization; attempted to call method 'widget'), until you change the name attribute from one form element (buttongroup or select).

F.e.:
Change the name attribute from the select element from name="q" to name="q-other-name"

Demo: http://jsfiddle.net/danielkoch/zRFSr/4/

And the two components will work together. The problem is, that the logic of the form also changes. I need to have the same name attribute on both elements.

**Comment by fnagel** [comment] 2013-04-23 07:09
I'm not able to reproduce the problem in latest FF:
http://fiddle.jshell.net/danielkoch/zRFSr/show/light/
I guess your "fix" by changing name attribute is just a lucky coincidence.

Anyway, you are including jQuery UI mutliple times which could cause the
problems.
Please use one of my prepared jsFiddles, see #61

Please note the is a new,m built from scratch version, see #140

**Comment by fnagel** [comment] 2013-05-29 18:04
Any feedback on this issue?

**Comment by fnagel** [comment] 2013-09-07 14:24
Closed as no feedback was given.

**Closed as completed by fnagel** 2013-09-07 14:24 UTC
Labels: bug, needs_feedback
