### ISSUE TITLE
Scroll Broken in FF

### ISSUE THREAD

**Issue by michaelcaplan** [fnagel/jquery-ui#30] opened 2010-11-12 18:00 UTC
with maxHeight set, I can't seem to scroll the list with either the up or down arrows, or by click on the scroll bar "white space."  I can scroll with the slider, or keyboard.  Doesn't seem to be an issue in IE (tested in 9)

**Comment by fnagel** [comment] 2010-11-13 00:16
Would you please provide a fully working zip with an example as I cant reproduce your problem. Please use the latest commit.

**Comment by sirsk** [comment] 2010-11-19 04:54
probably thats the same happends to me..
here a video ...
http://www.youtube.com/watch?v=Dq29zMsHZWk

**Comment by fnagel** [comment] 2010-11-28 23:05
The video has been removed.

**Comment by sirsk** [comment] 2010-11-28 23:37
The video has been reuploaded !
http://www.youtube.com/watch?v=Dq29zMsHZWk

**Comment by fnagel** [comment] 2010-11-28 23:42
I dont think that your problem is similar. Problem could be your video is very confusing. Why are the elements floating next to each other?
Please open an extra issue for this problem.

@michaelcaplan 
Please provide a example zip.

**Comment by fnagel** [comment] 2011-01-31 20:15
Closed as no feedback is given. Please re-open if necessary!

**Closed as completed by fnagel** 2011-01-31 20:15 UTC
Labels: bug, needs_feedback
