### ISSUE TITLE
How to avoid appearing animation on Chrome ?

### ISSUE THREAD

**Issue by cutmaster** [fnagel/jquery-ui#243] opened 2012-07-05 22:39 UTC
It seems that on Chrome only, there's a scroll style apparition of the select button (from right to left).
Why ? And how is it possible to avoid it ?
Thanks for your help.
:)

**Comment by fnagel** [comment] 2012-07-11 15:56
Please post a meaningful bug report with an example, see #61

**Comment by cutmaster** [comment] 2012-07-19 20:48
Hello,
You can find the "problem" here :
http://www.wptechnology.com/pics/selectMenuScroll.mov

It seems that, on webkit, if a select menu is inside a container that is in position:absolute and with a left attribute even like left:0px, the animation is shown from left to right. If the container is in position:absolute and, with a right attribute, the "animation" is shown from right to left.

Is there a way to avoid this ?

Thanks again for your help.

**Comment by fnagel** [comment] 2012-07-19 22:23
Sorry, but Im not able to play this video, not even with vlc. 

A demo fiddle would be really useful!

**Comment by cutmaster** [comment] 2012-07-19 22:42
Sorry the problem occur on a big website we're working on and extracting a part of our site, framework, etc just for a demo is really a big piece of cake.
I've uploaded the video as private on youtube where you can watch it here : 
http://www.youtube.com/watch?v=CKEwl0qPPuI&feature=youtu.be
As you can see, we've setted 5 different selectmenu (of different sizes), appearing in a modalbox (from jQueryUI), we didn't add any effect anywhere (no effect on modal dialog, no effect on div, blabla) and on firefox & IE the selectmenu showed fine, and not on chrome and safari...

**Comment by fnagel** [comment] 2012-07-20 20:30
Its pretty hard to understand the problem in this small viewport. Its a modalox with selectmenus and the problem is that they slide in from left to right, this happens only in Chrome, right?

Ive tested this in a fiddle and was not able to reproduce the issue: http://jsfiddle.net/GXtpC/525/embedded/result/

Did you tried to disable certain parts of the CSS? I would consider some unwanted side effects of some CSS statements. Im sorry, but I have no other idea how to help you :-/

**Comment by fnagel** [comment] 2012-08-30 19:23
Did you manage to solve your problem?

**Comment by fnagel** [comment] 2012-10-01 22:35
Any feedback on this issue?

**Comment by fnagel** [comment] 2012-10-12 20:35
Closed as issue seems to be solved. Please reopen if needed.

**Closed as completed by fnagel** 2012-10-12 20:35 UTC
Labels: bug, needs_feedback
