### ISSUE TITLE
ie8 - "Can't move focus to the control" after AJAX post

### ISSUE THREAD

**Issue by ircodebase** [fnagel/jquery-ui#216] opened 2012-02-14 16:29 UTC
Environment: 2 Dropdowns on page - 1st dropdown does an AJAX post with the post results populating the second dropdown. Upon selecting second dropdown ie8 throws "Can't move focus to the control"

Not sure if this breaks other things but works for my project so far :)

Line 583 of jquery.ui.selectmenu.js

//fix for ie8 bug Can't move focus to second control after ajax postback
//if (link.length) link[0].focus();
if (link.length && !(link.offsetHeight == 0)) link[0].focus();

**Comment by fnagel** [comment] 2012-02-14 21:39
Would you please post a demo fiddle? See #61

Im pretty sure youre using the Selectmenu widget wrong. Please see the issues for similar problem: https://github.com/fnagel/jquery-ui/issues/search?q=ajax

**Comment by fnagel** [comment] 2012-03-08 22:56
Any feedback on this issue?

**Comment by Misiu** [comment] 2012-05-15 11:46
I've got the same issue.
When I create an asp page and add selectmenu to it on my local machine everything works fine, on firefox, ie, but when I copy my page to asp server I have "Focus to control" problem, but only on IE. This is weird. I'll try to check my webserve, or I'll recreate my page from scratch, it's not so complicated.
I'll let You know about results.

**Comment by fnagel** [comment] 2012-05-15 22:59
Which version of jquery you are using?

**Comment by Misiu** [comment] 2012-05-16 06:06
I'm using jQuery version 1.7.20 and jQuery UI 1.8.20.
The error I had was not my fault or Your great code.
It was Microsoft fault - IE 8 renders differently content of local web server (IIS) and web server.
http://stackoverflow.com/questions/1867383/css-renders-differently-on-web-server-than-on-development-environment

What I had to do is to add this line to my page:

```
<meta http-equiv="X-UA-Compatible" content="IE=8"/>
```

Although it is weird that only selectmenu had errors, all others jQuery components (tabs, datepicker, autocomplete) worked fine.

**Comment by fnagel** [comment] 2012-05-16 14:28
Mhhh would you mind testing this with the jsFiddle versiojn (see #61) or the latest dev? 
Just because Selectmenu does not support jQuery 1.7.x yet.

@ircodebase 
Did you use jQuery 1.7.x too?

**Comment by fnagel** [comment] 2012-05-31 17:32
Ive updated Selectmenu to work with latest jQuery / UI versions. Please update and give feedback!

**Comment by Misiu** [comment] 2012-06-05 07:58
I replaced selectmenu with new version, for my needs it works ok (like previous version), but I must  add

``` PHP
<meta http-equiv="X-UA-Compatible" content="IE=8"/>
```

But as I was reading on stackoverflow, I must add this because of ASP and IIS weird behaviour.

One more question: Will select menu be pulled to official jQuery UI?

**Comment by fnagel** [comment] 2012-06-05 08:09
Mhh Im still not able to reproduce this. Without a demo I'm not willing to investigate further into this problem. 

Yes, but it has been written from scratch. Please see #140

@ircodebase Any feedback on your issue?

**Comment by Misiu** [comment] 2012-06-05 11:27
Will it be ok if I create an asp project in visual studio 2008?
I'll try to do it today and post it here.

**Comment by fnagel** [comment] 2012-06-05 12:25
Ahem, building websites in VS sounds awful to me but go ahead. As longs its editable by me (a zip?) and not too messy its ok.

**Comment by fnagel** [comment] 2012-07-11 18:14
Any feedback on this issue?

**Comment by fnagel** [comment] 2012-07-31 20:33
Any feedback on this issue?

**Comment by fnagel** [comment] 2012-08-30 19:24
Closed as no feedback was given. Please reopen if needed.

**Closed as completed by fnagel** 2012-08-30 19:24 UTC
Labels: bug, needs_feedback
