### ISSUE TITLE
selectmenu no longer working in IE8

### ISSUE THREAD

**Issue by jsm174** [fnagel/jquery-ui#191] opened 2011-11-15 16:41 UTC
I just upgraded to the 1.2.0 release of selectmenu. 

IE8 is reporting the following error when clicking anywhere in the control:

Webpage error details

Message: Can't move focus to the control because it is invisible, not enabled, or of a type that does not accept the focus.
Line: 579
Char: 21
Code: 0
URI: http://localhost:8080/test/js/jquery-ui-selectmenu/jquery.ui.selectmenu.js

```
        self._refreshPosition();    

        var link = selected.find("a");
    >   if (link.length) link[0].focus();       

        self.isOpen = true;
```

**Comment by fnagel** [comment] 2011-11-15 19:33
Damn it. Ive tested this again and again and I have absolutely no clue how I managed to miss that one :-(

Ive tested again in my Win7 IE8 VM and Im able to reproduce the error but the selectmenu does not break. In default demo IE8 throws one (!) error when initializing all selectmenus but it works as aspected when using the widget. I assume thats why Ive missed that error message.

Does the selectmenu break in your tests? What did you use for testing?

**Comment by jsm174** [comment] 2011-11-15 22:59
Yes. I can not get it to drop down / open up at all. 

I am using the selectmenu in a jquery ui tab. I'll take it out of the tab and see if that changes anything.

**Comment by fnagel** [comment] 2011-11-15 23:39
Would you mind posting a demo fiddle #61

Please give some info abut your OS!

**Comment by jsm174** [comment] 2011-11-16 15:51
Thanks. I played around with fiddle and I could not reproduce the issue. Then I finally figured it out. 

Our company finally upgrade to IE8 and put a group policy that forces internal sites to render in compatibility mode. When a doctype of <!DOCTYPE html> is used, Developer Tools shows "Browser Mode: IE8 Compat View Document Mode: IE7 Standards"

I added to the head  <meta http-equiv="X-UA-Compatible" content="IE=edge">

When the page is loaded, the document mode is set to IE8 Standards and select menu works properly.

So, I put a fiddle together. After you run it, go to developer tools and switch it to IE7 standards. Then you'll see the javascript error.

   http://jsfiddle.net/jsm174/GXtpC/156/

I hate IE..

**Comment by fnagel** [comment] 2011-11-23 21:20
Im currenlty pretty busy and not able to test this with VM. Am I right you solved this issue for now?

Would you mind test if 
    if (link.length) link.focus();
will fix this problem? 

Im not sure why we link[0] here, this code snippet was created by the original developer of this script. If link.focus() work I will need to test this asap in all relevant browsers and release a version 1.2.1.

Thanks for your contribution!

**Comment by BenKelada** [comment] 2011-12-02 01:06
the jsfiddle issue is caused by a missing closing div for      < div id="page" >
link[0] is correct, without link[0] IE link finds no element.
it is something to do with injecting the dropdown list into a malformed page.

**Comment by jsm174** [comment] 2011-12-02 02:36
I just went through this fragment and manually spaced out each line. 

   < div id="page"> 

is definitely closed. Just to triple check, I also ran it through HTML Tidy. It's definitely closed. 

It has something to do with the IE7 standards document mode. 

The respaced fiddle is at:

http://jsfiddle.net/jsm174/GXtpC/175/

**Comment by BenKelada** [comment] 2011-12-02 03:34
if you remove all the other elements except the select it seems to work even in ie7 standards mode

**Comment by BenKelada** [comment] 2011-12-02 03:41
lol actually if i remove id="page" from the div it works, if i add it back in it doesnt... bit strange, sorry for barging in!

**Comment by fnagel** [comment] 2011-12-04 23:49
Ive checked the fiddle and Im sure the markup structure is valid.

@berserkk is right, removing id=page fixes this. Perhaps its a jsfiddle problem / sideeffect? Did somebody tried to reproduce the error without jsfiddle involved?

**Comment by tschettler** [comment] 2011-12-07 17:09
I can reproduce the error without involving jsfiddle. I can't get a jsfiddle to reproduce the exact issue that I'm having, but I can get it to produce the error:
http://jsfiddle.net/tschettler/MrkyW/

This fiddle shows the error occurring when the menu does not have enough space to be displayed according to the height of the window. To reproduce, just play with the result dimensions, or go here for the full screen:
http://fiddle.jshell.net/tschettler/MrkyW/show/light/

I called selectmenu twice, because that's how the issue I'm facing appears, but it does not need to be called twice, or with any parameters. If there is not enough window height for the dropdown, it will not display it and will sometimes throw the error.

I'll try to reproduce the exact issue I'm having, but it has something to do with the following line not actually adding the class to the listwrap object:
self.listWrap.addClass(self.widgetBaseClass + '-open');

Since listwrap is still not visible, focus on the descendant link does not work.

If the menu opens up instead of down (due to window height), the error does not occur.

**Comment by tschettler** [comment] 2011-12-07 18:18
Found the resolution to my issue:

Change (line 444):
window.setTimeout(function () {
    self._refreshPosition();
}, 200);

To:
clearTimeout(this.refreshTimeout);
this.refreshTimeout = window.setTimeout(function () {
    self._refreshPosition();
}, 200);

Not sure if this will help with the other issues, but this fix is necessary if you initialize the selectmenu multiple times.

**Comment by tschettler** [comment] 2011-12-08 06:43
Sorry for hijacking the issue, I'll set it back on track. The reason why removing the id from the div works is because of the css:
#page {
   margin: 10px auto;
   width: 1000px;
}

After playing around a bit, I found that anything other than 0 or auto for the top and bottom margin value causes this issue. For example, the following css is fine:
#page {
   margin: 0 auto;
   width: 1000px;
}

As is:
#page {
   margin: auto;
   width: 1000px;
}

Not sure why this is the case.

**Comment by fnagel** [comment] 2012-01-18 22:20
So this issue could be closed?

**Comment by jsm174** [comment] 2012-01-19 02:10
I think it should. 

I confirmed the behavior with the auto margin that tschettler found.

I got around our corporate group policy "Browser Mode: IE8 Compat View Document Mode: IE7 Standards" by adding this meta tag:

< meta http-equiv="X-UA-Compatible" content="IE=edge"/>

**Comment by fnagel** [comment] 2012-01-26 18:54
Thanks for your feedback!

**Closed as completed by fnagel** 2012-01-26 18:54 UTC
Labels: bug, needs_feedback, IE

**Comment by ircodebase** [comment] 2012-02-14 17:53
Please reopen - this still occurs when there are 2 dropdowns on a page and the first dropdown does an ajax postback feeding the the second dropdowns item list.

 It looks like a temp workaround is by commenting out lines 448 to 452, or by increasing the refreshPosition time to a high number. I found this by quick clicking the second dropdown, and seeing it still working.

// needed when selectmenu is placed at the very bottom / top of the page
clearTimeout(this.refreshTimeout);
this.refreshTimeout = window.setTimeout(function () {
self._refreshPosition();
}, 200); /// changing this to 200000 allows the second dropdown to work

**Comment by fnagel** [comment] 2012-02-14 21:40
Please open a new issue with proper problem description and demo, see #61
