### ISSUE TITLE
On window resize (by user) selectmenu inverts

### ISSUE THREAD

**Issue by cosmohomeboy** [fnagel/jquery-ui#111] opened 2011-05-09 22:21 UTC
I am having some issues when the window is resized (by the user) with the selectmenu opened (in the process of being selected).  When there is no longer enough space available for the selectmenu to be displayed in its entirety, it inverts itself to be positions above the select.  The selectmenu that I am working on will be situated on the header, and when inverted is virtually useless (as well as unprofessional looking).  I am wondering if there is some way to disable this inversions feature?  I may have missed it whilst scouring the forums.  Any help is appreciated.

I tested it and found the same error on this site that was mentioned on some other posts:  http://wavemate.org/

**Comment by fnagel** [comment] 2011-05-11 09:45
Please take a look at the positing plugin and its options as we use this to postion the selectmenu (see collision).
http://jqueryui.com/demos/position/

You are able to pass these options by using the positionOptions option of selectmenu widget.

**Comment by cosmohomeboy** [comment] 2011-05-11 15:23
Fantastic.  I knew that there had to be a way around it.  I don't know if I am implementing it incorrectly or if there is another underlying issue, but I cannot get it working.  The script that I am running will be included at the bottom of the post.

I know that the positionOptions are working because in testing, when I change any of the three items listed (other than 'collision') the results are displayed on my test page.  Is there something else that I am doing incorrectly?  

Thank you for the response and the help.  Hope you get better from your surgery soon.  Thanks again for the plugin.  Great work!

```
<script>
    $(function(){   
        $('select#test').selectmenu({
            style: 'dropdown',
            width: 310,
            maxHeight: 1000,
            positionOptions: {
                my: "top",
                at: "bottom",
                offset: "0 0",
                collision: "none"
            }               
        });
    });
</script> 


```

**Comment by fnagel** [comment] 2011-05-23 17:52
Puhhh, it should work, but... Please try complete "none none" (double) values for option. Otherwise please provide a demo file with fiddle.

Are you running this with jQuery UI 1.8.x? There are some changes in UI 1.9 (afaik). Take a look at these changes if you need to use 1.9 https://github.com/fnagel/jquery-ui/pull/115

**Comment by amay** [comment] 2011-05-23 23:05
I'm having a similar issue where I would like to be able to pass `collision: 'none'` to position, and I think the issue is that you are not forwarding the collision option onto the position call. If you look at the position call (line 764) you can see the issue.
I have made a small change to fix this and issued a pull request: https://github.com/fnagel/jquery-ui/pull/117

**Comment by fnagel** [comment] 2011-05-24 08:02
Ahhh, this seems to be our problem! I will fix this asap.

**Comment by cosmohomeboy** [comment] 2011-05-24 19:12
Thanks for the help guys, I look forward to the fix.  As always, very pleased with the plugin, thanks for all you do.

**Comment by fnagel** [comment] 2011-05-24 20:43
Please take a look at the latest commit and give feedback!

**Comment by amay** [comment] 2011-05-25 00:27
I see you merged over the change, so looks good to me!

**Comment by fnagel** [comment] 2011-05-25 07:49
@cosmohomeboy
Does this solve your problem?

**Comment by cosmohomeboy** [comment] 2011-05-25 17:39
Yes, I already copied the changes over and everything is working perfectly.  Thanks for the help and the follow up.  I appreciate it.

**Comment by fnagel** [comment] 2011-05-26 09:21
Nice! Closed as resolved.

**Closed as completed by fnagel** 2011-05-26 09:21 UTC
Labels: question, needs_feedback
