### ISSUE TITLE
Unable to close the menu when clicking on HTML tag or BODY tag

### ISSUE THREAD

**Issue by Romanow88** [fnagel/jquery-ui#293] opened 2013-02-27 15:07 UTC
Please add this fix to the code:

<pre lang="javascript"><code>
        $( document ).bind( "mousedown.selectmenu-" + this.ids[ 0 ], function( event ) {
            //check if open and if the clicket targes parent is the same
            if (!event.target.offsetParent) {
                self.close(event);
                return;
            }
            if ( self.isOpen && self.ids[ 1 ] != event.target.offsetParent.id ) {
                self.close( event );
            }
        });
</code></pre>

**Comment by fnagel** [comment] 2013-03-02 16:17
Please post an example, see #61

**Comment by fnagel** [comment] 2013-03-26 21:53
Any feedback on this issue?

**Comment by Romanow88** [comment] 2013-03-26 22:01
Hi, don't know if I can reproduce this in jsfiddle, but it reproduses in ie9 and chrome on win7, win server 2003, 2007. Basically if you click on the body element when you have the drop down open you have a exception, saying that offsetparent is undefined. Hope this helps.

**Comment by fnagel** [comment] 2013-03-27 08:02
I cant reproduce it with default demo. I would need a minimal demo here.

**Comment by rosieks** [comment] 2013-05-28 06:32
I have the same issue when I click on body element (event.target is HTMLBodyElement). Value of HTMLBodyElement's `offsetParent` property is null.

**Comment by fnagel** [comment] 2013-05-28 07:54
Again: please post a minimal demo.

**Comment by rosieks** [comment] 2013-05-28 18:11
Here you are: http://jsfiddle.net/fnagel/GXtpC/embedded/result/
Just click on bottom of page (make sure that `event.target` is BODY and not DIV) when menu is opened. The problem occurs on IE9, IE10, Chrome 27

**Comment by Romanow88** [comment] 2013-05-28 18:35
That's what I was talking about.

**Comment by fnagel** [comment] 2013-05-28 19:56
Oh, shit. Thats a bad one. 

Problem confirmed, even in latest FF.

**Comment by fnagel** [comment] 2013-05-28 20:14
Problem is related to this one: #300

**Comment by fnagel** [comment] 2013-05-28 20:31
I've fixed this by reverting an old commit. Thanks for reporting!

Please check latest commit and give feedback!
Hopefully we'll not run into problems like this as the new Selectmenu has a bunch of unit tests.

**Comment by zalog** [comment] 2013-05-29 12:24
But now it work only when clicking on the html tag outside our html elements.
http://jsfiddle.net/fnagel/GXtpC/

**Comment by fnagel** [comment] 2013-05-29 17:58
Problem confirmed. Ive adopted the if clause we use in the new version. Works nice. 

Please test and give feedback!

**Comment by zalog** [comment] 2013-05-30 08:25
Works like a charm :+1:

**Comment by fnagel** [comment] 2013-09-07 14:23
Closed as fixed.

**Closed as completed by fnagel** 2013-09-07 14:23 UTC
Labels: bug, needs_feedback
