### ISSUE TITLE
selectmenu rendering changes when using ui-darkness

### ISSUE THREAD

**Issue by oleersoy** [fnagel/jquery-ui#197] opened 2011-11-30 22:22 UTC
If I change the css import in the demo from the current one to this:

```
<link   rel="stylesheet"
        type="text/css" 
        href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-darkness/jquery-ui.css"/>
```

The demo no longer displays right.  I tried finding a newer version to test with in the trunk, but it seems only the default theme is provided...

**Comment by fnagel** [comment] 2011-11-30 22:40
Mhh works nice for me, see: http://jsfiddle.net/GXtpC/172/

Demo link?

**Comment by oleersoy** [comment] 2011-11-30 23:44
It looks good here too.  I wonder if we are comparing apples to apples though.  I believe the fiddle is using different versions of jquery and jquery ui.  What I did was download the lastest 1.9 version you gave me earlier (Github).  I then changed only the css import in the demo default.html, and the selectmenu essentially breaks.

**Comment by oleersoy** [comment] 2011-12-01 03:37
I tried to create a fiddle with every single resource from the selectmenu branch, but it's not running for some reason:
http://jsfiddle.net/gwLYv/

In the process I realized that the original default.html demo css import included the selectmenu.css file.  When I replaced that import I neglected to include this file.  I have since included it, and it's not as broken as I thought it was...but still not quite right.

What I'm seeing is the width of the drop down menu is the width of the longest item in the list.  So for example in the selectmenu instance containing only numbers, the width of the drop down menu is the width of the biggest number.

**Comment by oleersoy** [comment] 2011-12-01 04:53
This is the css that I'm now importing in default.html:

```
<link   rel="stylesheet"
        type="text/css" 
        href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-darkness/jquery-ui.css"/>
<link   rel="stylesheet"
        type="text/css" 
        href="file:///home/ole/Desktop/jquery-jquery-ui-b539e2e/themes/base/jquery.ui.selectmenu.css"/>
```

Also - Did you look at the last two selectmenu instances in your fiddle?

**Comment by fnagel** [comment] 2011-12-01 19:32
Wait. What (which version of selectmenu) are we talking about? 
My posted fiddle inlcudes THIS branch (the "old" version) and it works fine (even the last two selectmenus) with themeroller.

This branch is not compatible with UI 1.9.x and this issue is not for talking about the new, built from scratch version. Please comment on #140 for that kind of purposes.

In your fiddle you linked LOCAL files. How is this supposed to work?

Ive added a demo for TS, take a look here: https://github.com/jquery/jquery-ui/commit/c00b685cb824fe940226be041067b0b9c44ba983

**Comment by oleersoy** [comment] 2011-12-01 22:54
Ooops - Sorry I'm trying learn Jquery, github, jsfiddle, etc. all at the same time and complete a project, so I'm a little more scattered than general.

I figured jsfiddle would recognize that the resource entered is a file URL, and upload the resource... apparently a bad assumption. 

I see that the selectmenu works fine when using the themeswitcher tool.  I'm not sure what I'm doing wrong.  If I take the css import:

```
<link rel="stylesheet" href="../../../themes/base/jquery.ui.all.css">
```

and replace it with:

<link   rel="stylesheet"
        type="text/css" 
        href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-darkness/jquery-ui.css"/>
    <link   rel="stylesheet"
        type="text/css" 
        href="file:///home/ole/Desktop/jquery-jquery-ui-c00b685/themes/base/jquery.ui.selectmenu.css"/>

The selectmenus don't display right....

Any ideas?

**Comment by fnagel** [comment] 2011-12-04 23:28
"file:///home/ole/Desktop/jquery-jquery-ui-c00b685/themes/base/jquery.ui.selectmenu.css"
is a local file too.

**Comment by oleersoy** [comment] 2011-12-05 05:38
Yes.  I'm trying to run the default.html demo with the UI darkness theme.  The above css links are from an experiment locally on my workstation.  It looks to me like importing ui-darkness from the cdn alone is not enough.  I therefore also imported the jquery.ui.selectmenu.css (From the built from scratch download).  However the selectmenu instances still look off (drop down arrows are on the wrong side, etc.).

**Comment by fnagel** [comment] 2011-12-05 14:13
Both versions work nice with themes. This is tested and confirmed. Problem
is definitely on your site.
Im willing to help, but its hardly possible with your delivered input:

1) I have still no clue which version we are talking about
2) You posted no valid example which makes it impossible for me ti debug
this issue

**Comment by oleersoy** [comment] 2011-12-05 14:48
Yes I can see how the widget does work when you are using the theme selector.  It works for me too.  However if I try to import the ui darkness theme via CDN into one of the demos, the display is off.   

I'm using this version (The one with the visual theme switcher test in it - issue 140):
https://github.com/jquery/jquery-ui/tree/selectmenu

If you try replacing the generic css theme with the ui darkness theme directly, I imagine you will see the same issues.

I'll be glad to email you a copy of my modified default.html if that helps?  I'm not sure how to create a fiddle since the release is not on CDN yet....

**Comment by fnagel** [comment] 2011-12-05 22:41
So you are using the unreleased dev version of selectmenu 2.0 which currently has some issues because of changes to Menu widget :-)

This branch (https://github.com/fnagel/jquery-ui/) should not be used for discussing selectmenu 2.0. Please use the jquery ui wiki, the jquery ui forum or the #140 issue.

Did you tried this file?
https://raw.github.com/jquery/jquery-ui/c00b685cb824fe940226be041067b0b9c44ba983/tests/visual/selectmenu/themeswitcher.html

That would work, just copy your file into a pastebin or send me an email with a zip: info @ felixnagel com

ps: you could link guthub files dircectly, see above (but CSS files wont work).

**Comment by oleersoy** [comment] 2011-12-06 00:59
Yes - see I have full trust in you :).   

OK - got it - I'll keep 140 stuff in the 140 branch from now on.  Here's a pastebin of what I'm talking about (140 Branch):

http://pastebin.com/tYZtxFLH

I took the themeswitcher.html file and commented out the jquery.ui.all.css and added the ui-darkness css from CDN.  If you place this file in the same folder as the themeswitcher.html file and open it in a browser, all the selectmenu widgets will look off.

I did the same process on the default.html demo file in the "Stable" select menu branch:
https://github.com/fnagel/jquery-ui/

I used to have issues with this, but I just checked again with a fresh download, and now it's fine.  Sweet!

If there's something you think I can help with on the 2.0 branch, please ask.  My email is ole.ersoy @ gmail.com.  Thanks.

**Comment by fnagel** [comment] 2011-12-06 21:13
You will need at least some files which will be included by the jquery.ui.all.css. 

Try this one: http://pastebin.com/MGkyY1hP

There is a problem with the .ui-menu style in the themed CSS file. Its not ready yet for the new Menu widget. I added a small fix in the posted code.

**Comment by oleersoy** [comment] 2011-12-07 05:13
I just tried it in Chrome and Firefox.  If I just place the contents in a file and open in a browser it works fine.

If I comment out jquery.ui.all.css and include ui-darkness from the CDN it looks off.  Same result if I leave jquery-ui.all.css in, and include the ui-darkness theme from the CDN right after that import.

**Comment by fnagel** [comment] 2011-12-07 11:30
Sorry, ive posted the original file, not my modified one. -.-

Here you go: http://pastebin.com/1jNPuKLZ

**Comment by oleersoy** [comment] 2011-12-07 15:50
Aha - I was scratching my head a little bit on that one :).  This works great in firefox and chrome.  Tested in both firefox 3.6.24 and Chrome 15.0.874.121.

I also tried it in Konquerer (Version 4.6.5 (4.6.5)).  On the first click the drop down menu is shifted to the left a little.  On subsequent clicks it appears normal.

**Comment by fnagel** [comment] 2011-12-07 23:42
Puuhhh Konquerer is not on my list nor on the compatibility list of jQuery UI afaik ;-)
What rendering engine does it use? Does it fail when no custom theme is used?

I think this should be fixed when the themes are tested for jQuery UI 1.9.x. Its all dev atm.

**Comment by oleersoy** [comment] 2011-12-08 00:02
Good question.  I thought Konquerer used WebKit and that's why I mentioned it.  Turns out it uses the KHTML rendering engine.

It has the same behaviour with the non customized test pages as well.  Seems like a browser bug.  It's only on the first click.  After that it's fine.

Great work on the selectmenu!  Do you want me to close the ticket?

**Comment by fnagel** [comment] 2011-12-08 22:39
I added a notice (http://wiki.jqueryui.com/w/page/12138056/Selectmenu) and will check this when our development is finished so far.

Thanks for your contribution!

**Closed as completed by fnagel** 2011-12-08 22:39 UTC
Labels: bug, needs_feedback

**Comment by oleersoy** [comment] 2011-12-09 00:32
Great - Fantastic work on this.  Thanks again for all the help!
