### ISSUE TITLE
selectmenu doesn't work w/o compatibility mode in IE

### ISSUE THREAD

**Issue by Globulopolis** [fnagel/jquery-ui#218] opened 2012-02-21 14:00 UTC
If I open page with menu in Internet Explorer 7 dropdown menu does not appear and IE thrown me an error. If I open page in over version's and with or not 'Compatibility mode' menu working as expect.

How can I fix this issue?

PS! Error raise on 11 line, but I thinks that's wrong.

**Comment by fnagel** [comment] 2012-02-21 14:23
Im not able to reproduce this problem in MS VM IE7 and the default demo.
How did you test?
Please provide a demo fiddle, see #61

ps: What is "over version's"

**Comment by Globulopolis** [comment] 2012-02-21 14:31
"over version's" I mean IE8/9

How to reproduce. Just create a page with default menu and open in IE9. After in "Developer tools"(F12) select "Browser mode" like IE7 and "Document mode" like IE7 and menu stop working.

**Comment by fnagel** [comment] 2012-02-21 14:46
Thats no valid way of testing. IEs built in compa modes are mostly useless
for JS testing.

Selectmenu default demo works for me in native IE7. Please test again and
give feedack.

**Comment by Globulopolis** [comment] 2012-02-22 07:03
Ok. I've tested plugin on the machine with IE7. No additional tuning with IE options. Just open page in browser... and nothing. Nothing work. All over UI working good(e.g. JQ UI button plugin).

Unfortunately I cannot provide an error that IE thrown to me. This is screenshot this a demo page(http://jsfiddle.net/fnagel/GXtpC/embedded/result/) http://i32.fastpic.ru/big/2012/0222/32/6c8aae73faf50f4d0bdc25d5b32f1132.jpg

**Comment by fnagel** [comment] 2012-02-22 18:16
Sorry, Im not able to reproduce this. Works great without problems on Microsofts Virtual Machine WebDev Images WinVista IE7.
Im sorry but Im not able to reproduce your problem. Ive asked a friend of mine which give me positive feedback in IE7, too. 

The screenshot youre sending is IE9, not IE7.

Try this link please: http://fiddle.jshell.net/fnagel/GXtpC/show/light/ Its without the iframe.

Not sure what to do. I need to reproduce the issue in order to fix it.

**Comment by fnagel** [comment] 2012-02-22 18:31
Mhh I can reproduce the problem in IE9! 

MIME type is sent wrong for CSS since ages (thats why the CSS is inline for jsFiddle), but JS MIME type seems to be wrong too. This breaks selectmenu in IE9 and every compa mode in IE9. 

See https://github.com/jsfiddle/jsfiddle-docs-alpha/issues/95 for more information. I need a new demo platform or a proxy to make this work again.

Everything works fine when tested locally or on your own servers.

**Comment by fnagel** [comment] 2012-02-22 21:30
Fiddle problem is now fixed. Latest fiddle uses a proxy for js and css files. Please update your fiddle!

**Comment by Globulopolis** [comment] 2012-02-23 08:00
Hmm...
Ok. JSFiddle works fine, but yesterday I test the script on the clear(new installed) machine(not virtual) with Win xp sp3 with IE7 by default.
Styles attached to select, and script build a proper structure(hidden select and span w/ <a> and over tags). But when I clicking on select for dropdown menu... Nothing happens. Dropdown menu doesn't appear.

Looking at code on JSFiddle I see that jQuery version is 1.6.4 (I'm using 1.7.1) and jQueryUI 1.8.16 (I'm using 1.8.17). It maybe a bug somewhere in this?

I need more testing... Later I will write about the test results.

**Comment by fnagel** [comment] 2012-02-23 08:38
jQuery 1.7.1 has some known issues, please search in the bugtracker. 1.8.17
should have no unwanted effects.

**Comment by Globulopolis** [comment] 2012-02-28 12:07
And again...
I'm rollback to jQuery 1.6.2 and jQueryUI 1.8.16

Tests nothing given to me. Unfortunately selectmenu won't work in strict IE7 mode(tested on win xp sp3). When I'm test that page in IE7 with compatibility mode selectmenu works fine for me.

**Comment by fnagel** [comment] 2012-03-08 22:47
So you have the same problem in 1.6.2? Or youre using 1.6.2 as it works for you?

I will try to find some time to fix the jQuery 1.7.x problems this weekend. We'll see if this helps us to track down your problem.

**Comment by fnagel** [comment] 2012-05-17 14:34
Ive updated Selectmenu to jQuery 1.7.2 and jQuery UI 1.8.20. There are some issues left, like fixing typeahead (see #213, help is appreciated!).

A general (not jQuery version related) problem with positioning in older IE was fixed before updating. This problem was introduced with the appendTo option and therefore only affects newer version of Selectmenu. Ive fixed this in version 1.2.1 (tagged release before updating to 1.7.2).

Please test latest commit and give feedback!

**Comment by fnagel** [comment] 2012-05-31 17:33
Any feedback on this issue?

**Comment by Globulopolis** [comment] 2012-06-01 07:50
Now it's worked as expect. Thanks for great work.

**Comment by fnagel** [comment] 2012-06-01 08:52
Great to hear. Thanks for your feedback!

**Closed as completed by fnagel** 2012-06-01 08:52 UTC
Labels: bug, needs_feedback, IE, Update-jQuery-version
