### ISSUE TITLE
Selectmenu button should be inline-block

### ISSUE THREAD

**Issue by betalb** [fnagel/jquery-ui#158] opened 2011-08-31 19:42 UTC
After setting wrapperElement to &lt;div&gt; by default selectmenu became block-level element.

Default browser select box is inline-block

Here is sample fiddle http://jsfiddle.net/nwFMs/

**Comment by fnagel** [comment] 2011-09-12 23:13
Thanks for your contribution.

I can confirm this issue on FF4. Any idea how to get rid of it? display: block seems to be necessary atm.

**Comment by betalb** [comment] 2011-09-23 09:23
Opened pull request with proposed fix

**Comment by fnagel** [comment] 2011-10-10 21:24
Closed as we have a pull request: #166

**Closed as completed by fnagel** 2011-10-10 21:24 UTC
Labels: bug
