### ISSUE TITLE
Chrome: Error when setting selectedindex = -1 and then try to open

### ISSUE THREAD

**Issue by sfradel** [fnagel/jquery-ui#134] opened 2011-06-12 22:15 UTC
The error occurs when trying to set focus in open method.
Putting this above focus call at least unblocks the control and resets its selected value.

if (this._selectedIndex() == -1){
                this.element[0].selectedIndex = 0;
                this._refreshValue();
            }

**Comment by fnagel** [comment] 2011-10-10 18:57
Sorry for the late response, I will take a look as soon as #147 is fixed. 

Perhaps you would like to test the new jQuery UI Selectmenu built from scratch? See #140

**Comment by fnagel** [comment] 2012-01-16 21:10
Would you mind test the latest commit?

**Comment by fnagel** [comment] 2012-03-08 22:53
Im not able to reproduce the problem, please test the latest commit and give feedback!

**Comment by fnagel** [comment] 2012-05-15 23:00
Closed as no feedback was given.

**Closed as completed by fnagel** 2012-05-15 23:00 UTC
Labels: bug, needs_feedback
