### ISSUE TITLE
On Window resize, selectmenu jumps to bottom of screen.

### ISSUE THREAD

**Issue by 422** [fnagel/jquery-ui#128] opened 2011-06-07 06:27 UTC
Hi fNagel,

We have followed the threads on here, and changes. However we still have this issue:

Build: fnagel-jquery-ui-selectmenu_v1.1.0-2-gf2865c1

Issue:
If we goto SelectMenu and default.

And before < / body > tag add a large print block of text.

....
Now scroll back to top of page. and choose: the menu "dropdown" Style

It should work fine yeah ?

Ok now grab the mouse and make the browser window ( our case FF4 ) narrower, by even a millimeter. Ensure the scroll bar is all the way up to the header....

Click the same select menu again, and the mouse jumps to the footer of the page. In fact its like the menu takes on a Bottom-Anchor all of it's self.

There is no need to post code, as this is off your standard demo, within the release version I posted above.

This is driving us crazy, even Todd at FilamentGroup was a bit bemused by our issue. Yet it seems to be "the new position technique" causing this.

**\* To Add ***
Once it has jumped to footer, and we try to select again, it is as if the menu resolves its positioning and doesnt do it again..
However resize the browser window again, and the issue re-occurs

**Comment by fnagel** [comment] 2011-06-07 23:27
I can confirm this issue with latest Chrome but not with FF4.

This issue seems to be related with the focus() within the open function and / or the window resize event at the end of function _create. What do you mean by saying "the new position technique" is causing this?

This needs further investigations.

**Comment by 422** [comment] 2011-06-07 23:31
Thanks for quick response :)
Sorry the position.js was just my stab at a guess. Apologies if that isnt the case.
The issue occurs in:

ff4 ff3 chrome and ie9
So pretty much the major 3 browsers.

**Comment by fnagel** [comment] 2011-06-07 23:35
3 major browsers is pretty bad :-(

I not quite sure if the window resize event is still needed so I will do some tests. The focus is needed for correct positioning in popup style.

**Comment by 422** [comment] 2011-06-07 23:38
Yeah focus seems to be the issue. To be fair, we have a very very comprehensive site, with masses of css and js functionality. I hadnt noticed until about 3 weeks ago, that this was indeed an issue ( after resizing the browser window )
We have now spent the last three weeks solidly going thru our code.. and thankfully we found another reported issue on here yesterday which now retains some sanity :)
The only other issue we have is that on firing up a browser with the select menu in , and it jumps to base of screen .. the drop down portion shifts to the right by approx 1 or 2 pixels.

**Comment by fnagel** [comment] 2011-06-07 23:44
Did you try to uncomment both mentioned lines? Both fix your problem as far as I can see.

I must confess Im not able to understand you last sentence. Please explain "firing up a browser" and "jumps to base of screen". Can you provide a demo (see #61) for this problem (and please open a new ticket for this ;-)?

**Comment by 422** [comment] 2011-06-07 23:48
Which 2 lines are those, we have tried many things ... and have now reverted to standard code.

Re:firing up the browser ( this is an issue to do with our css ) which resets when we refresh page. SO will keep investigating this.

**Comment by fnagel** [comment] 2011-06-08 00:00
Line 510 in latest commit (function open, line wih the focus) 

<pre>
this.list.addClass(self.widgetBaseClass + '-open')
                .attr('aria-hidden', false)
                .find('li:not(.' + self.widgetBaseClass + '-group):eq(' + this._selectedIndex() + ') a')[0].focus();
</pre>


Line 240 (the window resize event at the end of function _create)

<pre>
// needed when window is resized
$(window).bind( "resize.selectmenu", $.proxy( self._refreshPosition, this ) );
</pre>

**Comment by 422** [comment] 2011-06-08 00:08
Now I am confused: you state ( did you try to "uncomment both mentioned lines " )
Then post code which isnt uncommented in our jquery.ui.selectmenu.js

We have:

<pre>
this.list.addClass(self.widgetBaseClass + '-open')
                .attr('aria-hidden', false)
                .find('li:not(.' + self.widgetBaseClass + '-group):eq(' + this._selectedIndex() + ') a')[0].focus();
</pre>

and

<pre>
// needed when window is resized
        $(window).bind( "resize.selectmenu", $.proxy( self._refreshPosition, this ) );
</pre>


Are you stating we need to "comment" these out ? Because surely the code would then fail to open the dropdowns ?

**Comment by fnagel** [comment] 2011-06-08 08:15
Should look like this:

<pre>
this.list.addClass(self.widgetBaseClass + '-open')
                .attr('aria-hidden', false);
                //.find('li:not(.' + self.widgetBaseClass + '-group):eq(' + this._selectedIndex() + ') a')[0].focus();
</pre>

and

<pre>
// needed when window is resized
//$(window).bind( "resize.selectmenu", $.proxy( self._refreshPosition, this ) );
</pre>


Try modifiy one of the mentioned lines is enough to make it work again.

**Comment by 422** [comment] 2011-06-08 09:05
Pefect !!

Thanks Felix, really appreciate the fix :)

**Comment by fnagel** [comment] 2011-06-08 09:15
Naah, its not a fix yet. Perhaps the resize event is no longer needed but it was (not sure before or after the position changing).

**Comment by fnagel** [comment] 2011-06-16 21:55
Probably related: https://github.com/fnagel/jquery-ui/issues/96

**Comment by fnagel** [comment] 2011-08-01 23:38
I hopefully solved this problem. Please test the latest commit and give feedback.

I will close this one as multiple issues are affected. Please see this #147 summery and give feedback there!

**Closed as completed** 2011-08-01 23:39 UTC
Labels: bug, help_wanted

**Comment by fnagel** [comment] 2011-10-24 19:29
I feel cautiously optimistic Ive found a solution for this whole flickering/jumping/positioning issue. Finally. See and comment #147
