### ISSUE TITLE
Crashes Safari on iPad on orientation change

### ISSUE THREAD

**Issue by optimadesign** [fnagel/jquery-ui#139] opened 2011-06-28 17:39 UTC
Hi

I am using the jquery ui select plugin and it has been working great apart from one small issue with Safari on the iPad. 

It seems that when I have three or more select menus on a page and switch the iPad from portrait to landscape it causes Safari to crash. 

If I remove jquery ui select from the equation no crashing occurs.

Can anybody suggest how I might get around this?

Many thanks

**Comment by fnagel** [comment] 2011-06-28 23:04
Uhh thats a strange bug and Im not quite sure how to solv this as I have no iPad for testing. But we've planned to deactivate the menu from pop up and show the native option select instead on mobile devices. Perhaps that could help: https://github.com/fnagel/jquery-ui/issues/73

**Comment by fnagel** [comment] 2011-08-08 08:40
I tested the latest commit with an iPad and was not able to verify any problem (except the missing scrollbar support, shity crapple). Would you please test the latest commit? Ive used the default demo.

**Comment by fnagel** [comment] 2011-08-18 20:35
Please give some feedback!

**Comment by fnagel** [comment] 2011-09-12 22:54
Any feedback on this?

**Comment by xequalsloser** [comment] 2011-09-26 18:13
I had similar problems when using a very jquery-ui heavy layout (this plugin included). I'm not sure which ui element was causing the crash, honestly, but it seems to be related to how the page is zoomed. I was able to kill the error by disabling the user's ability to zoom with a meta-tag:

```
<meta name="viewport" id="view" content="user-scalable=yes, width=device-width minimum-scale = 1, maximum-scale = 1" />
```

Again, I'm not sure if it was caused by the selectmenu or one of the other dozen plugins on my page, but it does appear to be the same issue I was having.

**Comment by fnagel** [comment] 2011-09-26 18:29
Ahh nice! Thanks for your feedback, I was about to close this issue because I was not able to reproduce this one.

As I tested the default.hml demo (with about 7 selectmenu widgets active) it seems to me this is not a problem of the widget itself. 
Can somebody give a demo for testing purposes? I would need a test case to investigate this.

@xequalsloser
Seems like a nice approach. When did it crash? When aselectmenu is opened or just by init it and doing an orientation change?

@optimadesign
Im confused, didnt you post something like this?

<pre>
Hi

I am using the jquery ui select plugin and it has been working great apart from one small issue with Safari on the iPad.

It seems that when I have three or more select menus on a page and switch the iPad from portrait to landscape it causes Safari to crash.

If I remove jquery ui select from the equation no crashing occurs.

Can anybody suggest how I might get around this?

Many thanks
</pre>


Where is your post gone? Did you delete it?

**Comment by xequalsloser** [comment] 2011-09-26 18:41
Just an orientation change. It wasn't a consistent bug, either. Sometimes it would take eight to ten times before it would freeze up. I noticed that sometimes Safari would zoom in a bit when you change orientations, and that zooming it back out before rotating it again would sometimes delay the crash. I'm not 100% sure how mobile safari operates, but it's my guess that it redraws the whole page when it flips, and that occasionally that will hang up the ability to render everything properly.

But that's a wild guess, so don't quote me on it.

**Comment by fnagel** [comment] 2011-09-26 19:27
But your above posted snippet will fix this?

**Comment by xequalsloser** [comment] 2011-09-26 19:50
It seems to be working so far, but you sacrifice the ability to pinch-zoom the page.

**Comment by fnagel** [comment] 2012-07-31 20:34
Any news on this issue?

**Comment by fnagel** [comment] 2012-10-13 21:37
Could anyone please test this issue with v1.3.0?

**Comment by brlewis** [comment] 2013-11-20 19:42
Since this bug is two years old it wouldn't surprise me if Apple fixed it on the Mobile Safari end already.

**Comment by fnagel** [comment] 2014-09-30 15:37
Closed as outdated.

**Closed as completed by fnagel** 2014-09-30 15:37 UTC
Labels: bug, help_wanted, mobile
