### ISSUE TITLE
JqueryUI Selectmenu - Can't move focus to the control 

### ISSUE THREAD

**Issue by dkedar** [fnagel/jquery-ui#331] opened 2014-03-12 13:39 UTC
I am using the JqueryUI Selectmenu Plugin in one of my Application, The plugin works fine, In all Browsers, 
Only I am facing one issue in IE7 that is -  In IE7 if I click on the Select menu its give the Error note into Status bar. The error message is as follow.. although its working but still showing the message in status bar

Error Message: Can't move focus to the control because it is invisible, not enabled, or of a type that does not accept the focus.

Its is happens with in only IE7 and on old PC.

Can anyone have any  solution for fix this Error message?

Thanks
Kedar

**Comment by fnagel** [comment] 2014-03-12 17:00
Are you sure you are using the latest version and a compatible jQuery / UI version? We had this issue some time ago and it should be fixed. 

Otherwise please provide a demo fiddle see #61

**Comment by dkedar** [comment] 2014-03-13 09:53
I am facing this issue in the web app that is currently under construction. there are lot''s of javascripts included previously by another developers, duplicated Jquery files are also included into that app, 

Unfortunately I cannot remove those because some other java script's depended upon that. currently I am revamping this app.

If you are having IE8 installed and using IE7 browser and document mode and when you click on the select menu then this error message showing into status bar of IE but Select menu still working.

In this situation, I want to fix that error message some how. If you want to see view-source of the page, then I can provide you the text file.

Please let me know

**Comment by fnagel** [comment] 2014-03-13 14:52
I would need a minimal example of your code, or even better, a demo fiddle in which your are able to reproduce the issue. This a spare time project and I'm not willing to help out in such specific cases with limited insights. I'm currently to busy, sorry :-/

Having multiple jQuery versions included is known to cause issues. Perhaps you could remove as much as possible in order to limit the issue causing options?
Try search this GitHub repo for your error message, there are some code snippets which could help (but you need to change the selectmenu code).

You could give the new, upcoming version of jQuery UI Selectmenu a try. It's currently in the master branch of jQuery UI: https://github.com/jquery/jquery-ui

**Comment by dkedar** [comment] 2014-03-19 06:56
ok, thanks
I will try to remove duplicated Jquery UI first, will see if problem is fixed or not, I will also make sure that I am using latest Jquery UI

**Comment by fnagel** [comment] 2014-06-01 12:50
Any feedback on this issue?

**Comment by j3lte** [comment] 2014-06-10 12:08
I am facing the same problem. We use a legacy version of jQuery (1.7.2) which is in our central repository. Also, we use jquery UI 1.8.23.

Now, here is the strange part... We have to be compatible with IE8. And so we test everything on IE8. Our application is in 2 languages: Dutch (nl) and English (en). If I switch to Dutch, it IS working. I trigger selectmenu('open') on IE8, it works.... But then... I switch to English and all of a sudden it stops working.

It is by far the strangest error I have ever witnessed. The difference between English and Dutch in our application is : 
- html lang="xx"
- All the text and labels are translated (Using Java Spring). 

I have checked, rechecked everything. The whole HTML is the same with the exception of the language strings. Everything else is EXACTLY the same. But, it is still not working on EN, while it does on NL. I am currently digging into this problem. Already have updated the plugin to the 1.3.0. Working to see where the differences are...

**Comment by fnagel** [comment] 2014-06-10 12:22
@j3lte Please provide a demo as described in #61. A demo link would be helpful too here.

Until now, I assume the OP issue was caused by multiple jQuery files.

**Comment by j3lte** [comment] 2014-06-10 14:38
Well the problem is that this code is private, as in, it is an internal application. So it's hard to reproduce this problem with a simple demo. Nevertheless, I will try to see if I can create something in Plunker or JSBin. Unfortunately, due to time pressure, I have resorted to a different plugin to solve it for now...

**Comment by fnagel** [comment] 2014-06-10 14:43
Ahh ok, I'm happy to help but I would need something to reproduce the issue. 

Are you aware there is a (rewritten) selectmenu widget coming with the next jQuery UI release? See here: http://blog.jqueryui.com/2014/05/jquery-ui-1-11-0-beta-2/

**Comment by fnagel** [comment] 2014-09-01 09:18
Any feedback on this issue?

**Comment by fnagel** [comment] 2014-09-30 15:36
Closed as no feedback was given. Please reopen if needed.

**Closed as completed by fnagel** 2014-09-30 15:36 UTC
Labels: bug, needs_feedback
