### ISSUE TITLE
eventPropagation for _toggle event

### ISSUE THREAD

**Issue by escapedcat** [fnagel/jquery-ui#274] opened 2012-10-15 09:12 UTC
I'm using UIs datepicker and your selectmenu on the same page.

Problem was, that if I open the datepicker and click the selectmenu, the closing event for the datepicker isn't triggered, because the event is not bubbling up.

I tried to only exchange "return false" with "preventDefault", but than also the close event for the selectmenu is triggerd immediately after click to open it. I changed the binded event for closing the selectmenus to check the parent-id to avoid closing itself but keep bubble up and trigger other events (close datepicker i.e.).

Totally not sure if this a clean solution. Doesn't look like it, but at least I wanted to let you know and provide my solution.

This is a fiddle with my 'fix':
http://jsfiddle.net/escapedcat/GXtpC/722/

Also here is the diff with my changes:
https://github.com/escapedcat/jquery-ui/commit/690bbee3f0798ba944111f46d10f540803b7f224

**Comment by fnagel** [comment] 2012-10-25 22:50
Problem confirmed. Fix seems to work nice. 

Is this related to this problem? #238

Did you test this on different browsers?

**Comment by escapedcat** [comment] 2012-11-02 08:37
Ah, yes... duplicate of that one.

I tested the fiddle in Chrome and Firebox (both latest). The IE9 has problems with the fiddle due to the script embedding of jsfiddle (I guess), but it's working fine in our project in Chrome/FF/IE9.

**Comment by fnagel** [comment] 2012-11-10 01:27
Merged and pushed. Thanks for your contribution.

**Comment by fnagel** [comment] 2013-05-07 19:36
Hey @escapedcat  would you mind checking this one out? #300 It seems its related to you fix. Any idea?

**Comment by fnagel** [comment] 2013-09-07 14:27
Closed as seems to be fixed.

**Closed as completed by fnagel** 2013-09-07 14:27 UTC
Labels: bug, needs_feedback
