### ISSUE TITLE
focus lost in certain cases

### ISSUE THREAD

**Issue by phazei** [fnagel/jquery-ui#22] opened 2010-10-07 19:56 UTC
When done in dropdown style, or when list is completely above or below box, if you click and click the box again closing it, without selecting anything new, it loses focus.  After that you can't use the arrows unless you tab away and tab back.

**Comment by fnagel** [comment] 2010-11-09 21:48
This bug is confirmed. Accessibility issue.

**Comment by fnagel** [comment] 2010-11-29 00:47
Thanks for reporting. The problem was a missing parameter in this.newelement mousedown event. 

Fixed in latest commit.

**Closed as completed by fnagel** 2010-11-29 00:47 UTC
Labels: bug, accessibility

**Comment by pdias** [comment] 2013-06-01 18:03
Hello, i have this problem... but i'm using selecmenu within a dialog.

Ideas to solve?

Thanks,

Paulo

**Comment by fnagel** [comment] 2013-06-01 18:11
Please open a new issue with reference to this one, see #61
