### ISSUE TITLE
Type-ahead doesn't work with jQuery 1.7.1

### ISSUE THREAD

**Issue by cberner** [fnagel/jquery-ui#213] opened 2012-01-31 01:41 UTC
type-ahead in the selectmenu doesn't work properly (highlighting doesn't work, and arrow keys don't work) when used with jQuery 1.7.1, even though it seems to work with 1.6.2

**Comment by ubuntux** [comment] 2012-02-10 02:38
This bug is proven... I had the same issue when I tried to upgraded jQuery from 1.6.2 to 1.7.1

**Comment by fnagel** [comment] 2012-02-22 21:33
Any idea how to fix this?

**Comment by cberner** [comment] 2012-02-22 21:43
Unfortunately not, I ended up using a different library instead.

On Wed, Feb 22, 2012 at 1:33 PM, Felix Nagel <
reply@reply.github.com

**Comment by fnagel** [comment] 2012-05-17 14:23
Ive just updated Selectmenu to jQuery 1.7.2 and can confirm this problem. Any help is appreciated!

**Comment by fnagel** [comment] 2012-05-17 16:58
Ive just tested this again and it seems it works pretty normal. Tested in latest FF, IE9 and IE7.

Please test latest commit and give feedback!

**Comment by cberner** [comment] 2012-06-26 21:02
Going to be at Google I/O this week, but I'll try to test it out next week, and let you know!

**Comment by fnagel** [comment] 2012-06-27 21:40
There is a confirmed issue when using up down arrow in opened menu, see #240

**Comment by cberner** [comment] 2012-07-02 00:04
Ok cool, well I'll try to test it after that's fixed then

**Comment by fnagel** [comment] 2012-07-12 09:47
Above mentioned issue seems to be fixed with #247. Please test and give feedback!

**Comment by fnagel** [comment] 2012-07-31 20:31
Any feedback on this issue?

**Comment by cberner** [comment] 2012-07-31 20:51
Still seems like it's not working. I didn't do the implement myself (my partner did), but you can see it on our site: http://carsabi.com/car-search/

**Comment by fnagel** [comment] 2012-08-06 20:35
Mhh this seems to be related to your specific website. I'm not able to reproduce it in a fiddle. Are you?

**Comment by fnagel** [comment] 2012-08-30 19:25
Any feedback on this issue?

**Comment by fnagel** [comment] 2012-10-01 22:36
Any feedback on this issue?

**Comment by fnagel** [comment] 2012-10-12 20:36
Closed as issue seems to be solved. Please reopen if needed.

**Closed as completed by fnagel** 2012-10-12 20:36 UTC
Labels: bug, needs_feedback, Update-jQuery-version
